/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum BUY_SELL_OMSS { 
  BUYI, SELL, EXERCISEOPT, RCVPREM, RCVSECAMT, PAYSECAMT, PAYFIXRATE, RCVFIXRATE, PAYSPREAD, RCVSPREAD, RCVCCY, PAYCCY, RCVDIV, PAYDIV, BUYPROT, SELLPROT, RCVCMDTY, DELCMDTY  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"BUY_SELL_OMSS\",\"namespace\":\"com.commerzbank.domain\",\"symbols\":[\"BUYI\",\"SELL\",\"EXERCISEOPT\",\"RCVPREM\",\"RCVSECAMT\",\"PAYSECAMT\",\"PAYFIXRATE\",\"RCVFIXRATE\",\"PAYSPREAD\",\"RCVSPREAD\",\"RCVCCY\",\"PAYCCY\",\"RCVDIV\",\"PAYDIV\",\"BUYPROT\",\"SELLPROT\",\"RCVCMDTY\",\"DELCMDTY\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
