/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum CLNT_INT_ID_TYPES { 
  COKIS, BPKN, ISIS, LEI, DPTNR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CLNT_INT_ID_TYPES\",\"namespace\":\"com.commerzbank.domain\",\"symbols\":[\"COKIS\",\"BPKN\",\"ISIS\",\"LEI\",\"DPTNR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
