/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum FIN_INSTR_ID_INT_TYPES { 
  ISIN, WPKN, CUSIP, IDDS, INTID, SEDOL, RIC, RED, BBG, EXTS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"FIN_INSTR_ID_INT_TYPES\",\"namespace\":\"com.commerzbank.domain\",\"symbols\":[\"ISIN\",\"WPKN\",\"CUSIP\",\"IDDS\",\"INTID\",\"SEDOL\",\"RIC\",\"RED\",\"BBG\",\"EXTS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
