/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum OPTION_TYPES_OMS { 
  CALL, PUTO, OTHR, CAP, FLOOR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OPTION_TYPES_OMS\",\"namespace\":\"com.commerzbank.domain\",\"symbols\":[\"CALL\",\"PUTO\",\"OTHR\",\"CAP\",\"FLOOR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
