/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum OPTION_EXERCISE_STYLES { 
  EURO, AMER, ASIA, BERM, OTHR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OPTION_EXERCISE_STYLES\",\"namespace\":\"com.commerzbank.domain\",\"symbols\":[\"EURO\",\"AMER\",\"ASIA\",\"BERM\",\"OTHR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
