/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ORDER_RESTRICTION_TYPES { 
  SESR, VFAR, VFCR, OTHR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ORDER_RESTRICTION_TYPES\",\"namespace\":\"com.commerzbank.domain\",\"symbols\":[\"SESR\",\"VFAR\",\"VFCR\",\"OTHR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
