/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ORDER_EVNT_CODE_TYPES { 
  RFQ, QUOT, INCOR, OUTOR, EXCOR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ORDER_EVNT_CODE_TYPES\",\"namespace\":\"com.commerzbank.domain\",\"symbols\":[\"RFQ\",\"QUOT\",\"INCOR\",\"OUTOR\",\"EXCOR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
