/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ORDER_ACTN_TYPES { 
  NEWO, CANCL, RJCT, TRIG, REME, REMA, REMH, CHME, CHMO, CAME, CAMO, EXPI, PARF, FILL, INACT, REMO, CACL, RJTCL, CAEXC  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ORDER_ACTN_TYPES\",\"namespace\":\"com.commerzbank.domain\",\"symbols\":[\"NEWO\",\"CANCL\",\"RJCT\",\"TRIG\",\"REME\",\"REMA\",\"REMH\",\"CHME\",\"CHMO\",\"CAME\",\"CAMO\",\"EXPI\",\"PARF\",\"FILL\",\"INACT\",\"REMO\",\"CACL\",\"RJTCL\",\"CAEXC\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
