/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum PASSV_AGGR_INDS { 
  PASS, AGGR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PASSV_AGGR_INDS\",\"namespace\":\"com.commerzbank.domain\",\"symbols\":[\"PASS\",\"AGGR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
