/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum PRICE_NOTATION_TYPES { 
  MONE, PERC, YIEL, BAPO  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PRICE_NOTATION_TYPES\",\"namespace\":\"com.commerzbank.domain\",\"symbols\":[\"MONE\",\"PERC\",\"YIEL\",\"BAPO\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
