/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum QTY_NOTATION_TYPES { 
  UNIT, NOML, MONE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"QTY_NOTATION_TYPES\",\"namespace\":\"com.commerzbank.domain\",\"symbols\":[\"UNIT\",\"NOML\",\"MONE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
