/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum QUOTE_CXL_REASONS { 
  MKTDIST, LMTEXH, OUTFM, OUTTECH, OTHR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"QUOTE_CXL_REASONS\",\"namespace\":\"com.commerzbank.domain\",\"symbols\":[\"MKTDIST\",\"LMTEXH\",\"OUTFM\",\"OUTTECH\",\"OTHR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
