/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum SEND_ENTITY_ID_TYPES { 
  COKIS, BPKN, ISIS, INTID, DPTNR, LEI  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SEND_ENTITY_ID_TYPES\",\"namespace\":\"com.commerzbank.domain\",\"symbols\":[\"COKIS\",\"BPKN\",\"ISIS\",\"INTID\",\"DPTNR\",\"LEI\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
