/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum SHORT_SELLING_INDS { 
  SSHO, SSEX, SELL, UNDI  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"SHORT_SELLING_INDS\",\"namespace\":\"com.commerzbank.domain\",\"symbols\":[\"SSHO\",\"SSEX\",\"SELL\",\"UNDI\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
