/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum VALIDITY_PERIOD_INDS { 
  GDAY, GTCA, GTHT, GTHD, GTDT, GAFT, GAFD, GADT, IOCA, FORK, OTHR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"VALIDITY_PERIOD_INDS\",\"namespace\":\"com.commerzbank.domain\",\"symbols\":[\"GDAY\",\"GTCA\",\"GTHT\",\"GTHD\",\"GTDT\",\"GAFT\",\"GAFD\",\"GADT\",\"IOCA\",\"FORK\",\"OTHR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
