/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain.omega;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum BUY_SELL { 
  BUYI, SELL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"BUY_SELL\",\"namespace\":\"com.commerzbank.domain.omega\",\"symbols\":[\"BUYI\",\"SELL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
