/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain.omega;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum COUNTERPARTY_ID_TYPES { 
  COKIS, BPKN, ISIS, DPTNR, LEI  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"COUNTERPARTY_ID_TYPES\",\"namespace\":\"com.commerzbank.domain.omega\",\"symbols\":[\"COKIS\",\"BPKN\",\"ISIS\",\"DPTNR\",\"LEI\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
