/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain.omega;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum OPTION_TYPES { 
  CALL, PUTO, OTHR  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"OPTION_TYPES\",\"namespace\":\"com.commerzbank.domain.omega\",\"symbols\":[\"CALL\",\"PUTO\",\"OTHR\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
