/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain.omega;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum ORD_ID_EXT_TYPES { 
  TRDVN, BROK, CLNT  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ORD_ID_EXT_TYPES\",\"namespace\":\"com.commerzbank.domain.omega\",\"symbols\":[\"TRDVN\",\"BROK\",\"CLNT\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
