/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain.omega;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum PTT_EXMPT_REASONS { 
  PORTF, PCKGTRX, ESCB  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"PTT_EXMPT_REASONS\",\"namespace\":\"com.commerzbank.domain.omega\",\"symbols\":[\"PORTF\",\"PCKGTRX\",\"ESCB\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
