/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain.omega;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum STRIKE_PRICE_NOTATION_TYPES { 
  MONE, YIEL, PERC  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"STRIKE_PRICE_NOTATION_TYPES\",\"namespace\":\"com.commerzbank.domain.omega\",\"symbols\":[\"MONE\",\"YIEL\",\"PERC\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
