/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain.omega;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum STTLM_DELIVERY_TYPES { 
  PHYS, CASH, OPTL  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"STTLM_DELIVERY_TYPES\",\"namespace\":\"com.commerzbank.domain.omega\",\"symbols\":[\"PHYS\",\"CASH\",\"OPTL\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
