/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain.omega;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum TRADING_CAPACITY_INDS { 
  DEAL, MTCH, AOTC  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"TRADING_CAPACITY_INDS\",\"namespace\":\"com.commerzbank.domain.omega\",\"symbols\":[\"DEAL\",\"MTCH\",\"AOTC\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
