/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.commerzbank.domain.omega;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum WAIVER_IND_TYPES { 
  LRGS, RFPT, NLIQ, OILQ, PRIC, SIZE, ILQD, ESCB  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"WAIVER_IND_TYPES\",\"namespace\":\"com.commerzbank.domain.omega\",\"symbols\":[\"LRGS\",\"RFPT\",\"NLIQ\",\"OILQ\",\"PRIC\",\"SIZE\",\"ILQD\",\"ESCB\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
